# A possibly incomplete Demo of all the combinations of indexing methods
... and interesting cases

In [3]:
import numpy as np

# 1d Array

In [4]:
a = np.array(list("ABCDEFHIJKLMNOPQRSTUVWXYZ"))
a

array(['A', 'B', 'C', 'D', 'E', 'F', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
       'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

### \[int]

In [5]:
a[9]

'K'

### \[slice]

In [6]:
a[2::3]

array(['C', 'F', 'J', 'M', 'P', 'S', 'V', 'Y'], dtype='<U1')

### \[array]

In [7]:
a[[1,2,3]]

array(['B', 'C', 'D'], dtype='<U1')

# 2D Array

In [8]:
a = np.array(list("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")).reshape(6,6)
a

array([['A', 'B', 'C', 'D', 'E', 'F'],
       ['G', 'H', 'I', 'J', 'K', 'L'],
       ['M', 'N', 'O', 'P', 'Q', 'R'],
       ['S', 'T', 'U', 'V', 'W', 'X'],
       ['Y', 'Z', '0', '1', '2', '3'],
       ['4', '5', '6', '7', '8', '9']], dtype='<U1')

### Field access Indexing \[int\]\[int\]

In [9]:
a[3][4]

'W'

### Regular Indexing \[int, int\]
usually you index within one square bracket

In [10]:
a[3, 4]

'W'

Behind the scenes, the comma causes the indexes to be interpreted as a tuple, so explicitely indexing with tuples also works!

In [13]:
a[(3, 4)]

'W'

### Mixing and matching \[int, slice], \[slice, int], \[int, array], \[array, int]
When one index refers to multiple elements and the other does not, the int dimension gets eaten! You end up with a 1D array of the lenth of the multi-element index

In [16]:
a[3, ::2]

array(['S', 'U', 'W'], dtype='<U1')

In [17]:
a[3, [1,2]]

array(['T', 'U'], dtype='<U1')

### \[slice, slice], \[slice, array], \[array, slice]
When both indexes refer to multiple elements (and at least one of them is a slice) you get orthogonal indexing. You can think of it as subsetting the original array.

In [18]:
a[::2, 1::2]

array([['B', 'D', 'F'],
       ['N', 'P', 'R'],
       ['Z', '1', '3']], dtype='<U1')

In [19]:
a[::2, [1,2,3]]

array([['B', 'C', 'D'],
       ['N', 'O', 'P'],
       ['Z', '0', '1']], dtype='<U1')

### \[array, array]
When both indexes are arrays they act like lookup-coordinates for rows and columns. This is fancy indexing!

In [22]:
a[[3,3,0],[4,1,5]]

array(['W', 'T', 'F'], dtype='<U1')

Actually, orthogonal indexing is a subset of fancy indexing! The returned array size always corresponds to the indexing array size. In the case above we have two 1X3 arrays as indexes. When you index with a row and a column vector instead (see below), they get broadcast together to produce the same result you would get with the slice syntax.



In [20]:
np.ix_([0,2], [1,3,5])

(array([[0],
        [2]]),
 array([[1, 3, 5]]))

In [21]:
# get it to be orthogonal 
a[np.ix_([0,2], [1,3,5])]

array([['B', 'D', 'F'],
       ['N', 'P', 'R']], dtype='<U1')

### \[mdarray, slice\]
indexing with one multidimensionsional array also basically broadcasts them together to get the final shape

In [32]:
ix = np.array([[1,2],[1,2]])
ix

array([[1, 2],
       [1, 2]])

In [33]:
a

array([['A', 'B', 'C', 'D', 'E', 'F'],
       ['G', 'H', 'I', 'J', 'K', 'L'],
       ['M', 'N', 'O', 'P', 'Q', 'R'],
       ['S', 'T', 'U', 'V', 'W', 'X'],
       ['Y', 'Z', '0', '1', '2', '3'],
       ['4', '5', '6', '7', '8', '9']], dtype='<U1')

In [34]:
a[ix,:]

array([[['G', 'H', 'I', 'J', 'K', 'L'],
        ['M', 'N', 'O', 'P', 'Q', 'R']],

       [['G', 'H', 'I', 'J', 'K', 'L'],
        ['M', 'N', 'O', 'P', 'Q', 'R']]], dtype='<U1')

In [35]:
a[ix,:].shape

(2, 2, 6)

In [36]:
a

array([['A', 'B', 'C', 'D', 'E', 'F'],
       ['G', 'H', 'I', 'J', 'K', 'L'],
       ['M', 'N', 'O', 'P', 'Q', 'R'],
       ['S', 'T', 'U', 'V', 'W', 'X'],
       ['Y', 'Z', '0', '1', '2', '3'],
       ['4', '5', '6', '7', '8', '9']], dtype='<U1')

below you can see how the broadcasting works explicitely

In [39]:
print(np.broadcast_arrays([[1],[2]],[2,3]))
a[[[1],[2]],[2,3]]

[array([[1, 1],
       [2, 2]]), array([[2, 3],
       [2, 3]])]


array([['I', 'J'],
       ['O', 'P']], dtype='<U1')

In [40]:
print(np.broadcast_arrays([2, 3], [[1],[2]]))
a[[2, 3], [[1],[2]]]

[array([[2, 3],
       [2, 3]]), array([[1, 1],
       [2, 2]])]


array([['N', 'T'],
       ['O', 'U']], dtype='<U1')

the reason why fancy indexing works, is that they are also broadcast together but no changes are made

In [41]:
print(np.broadcast_arrays([2, 3], [1, 2]))

[array([2, 3]), array([1, 2])]


### Boolean Indexing

In [43]:
a = np.random.randint(0,10,(5,5))
a

array([[9, 6, 8, 0, 0],
       [1, 3, 4, 5, 7],
       [5, 1, 0, 6, 2],
       [2, 5, 9, 8, 1],
       [8, 6, 9, 0, 6]])

In [44]:
a<4

array([[False, False, False,  True,  True],
       [ True,  True, False, False, False],
       [False,  True,  True, False,  True],
       [ True, False, False, False,  True],
       [False, False, False,  True, False]])

In [45]:
a[a<4]

array([0, 0, 1, 3, 1, 0, 2, 2, 1, 0])

# 3+ D Indexing

In [47]:
a = np.random.randint(0,10,(3,4,5))
a

array([[[4, 4, 4, 5, 6],
        [6, 8, 1, 0, 0],
        [0, 0, 6, 9, 2],
        [1, 3, 3, 6, 8]],

       [[9, 6, 8, 3, 1],
        [5, 1, 5, 2, 2],
        [8, 1, 5, 9, 6],
        [7, 2, 3, 7, 5]],

       [[9, 7, 8, 3, 8],
        [8, 1, 5, 9, 5],
        [0, 4, 5, 6, 7],
        [8, 6, 7, 6, 5]]])

In [48]:
a.shape

(3, 4, 5)

### all ints

In [49]:
a[1,2,3]

9

### all slices

In [50]:
a[::2,::2,::2]

array([[[4, 4, 6],
        [0, 6, 2]],

       [[9, 8, 8],
        [0, 5, 7]]])

### arrays/fancy

In [52]:
a[[1,2],[1,2],[1,2]]

array([1, 5])

In [53]:
a

array([[[4, 4, 4, 5, 6],
        [6, 8, 1, 0, 0],
        [0, 0, 6, 9, 2],
        [1, 3, 3, 6, 8]],

       [[9, 6, 8, 3, 1],
        [5, 1, 5, 2, 2],
        [8, 1, 5, 9, 6],
        [7, 2, 3, 7, 5]],

       [[9, 7, 8, 3, 8],
        [8, 1, 5, 9, 5],
        [0, 4, 5, 6, 7],
        [8, 6, 7, 6, 5]]])

### Mixing it up \[slice, int, array\]
the single dimension gets eaten again

In [54]:
print(a[:,1,[1,2]])
print(a[:,1,[1,2]].shape)

[[8 1]
 [1 5]
 [1 5]]
(3, 2)


In [55]:
print(a[:,[1,2],1])
print(a[:,[1,2],1].shape)

[[8 0]
 [1 1]
 [1 4]]
(3, 2)


In [56]:
print(a[1, [1,2], :])
print(a[1, [1,2], :].shape)

[[5 1 5 2 2]
 [8 1 5 9 6]]
(2, 5)


In [78]:
print(a[[1,2], 1, :])
print(a[[1,2], 1, :].shape)

[[0 3 7 4 8]
 [8 8 7 2 5]]
(2, 5)


In [79]:
print(a[[1,2], :, 1])
print(a[[1,2], :, 1].shape)

[[7 3 0 9]
 [1 8 2 0]]
(2, 4)


In [82]:
print(a[0, :, [1,2]])
print(a[0, :, [1,2]].shape)

[[0 0 9 7]
 [7 7 8 5]]
(2, 4)


why not 4,2 you might ask?

slice in the middle -> slice dimensions always go at the back.

In [57]:
a

array([[[4, 4, 4, 5, 6],
        [6, 8, 1, 0, 0],
        [0, 0, 6, 9, 2],
        [1, 3, 3, 6, 8]],

       [[9, 6, 8, 3, 1],
        [5, 1, 5, 2, 2],
        [8, 1, 5, 9, 6],
        [7, 2, 3, 7, 5]],

       [[9, 7, 8, 3, 8],
        [8, 1, 5, 9, 5],
        [0, 4, 5, 6, 7],
        [8, 6, 7, 6, 5]]])

In [58]:
i1 = (np.arange(2*3*5) % 3).reshape(2,3,5)
i2 = (np.arange(2*3*5) % 5).reshape(2,3,5)

In [59]:
np.broadcast_arrays(i1, i2)

[array([[[0, 1, 2, 0, 1],
         [2, 0, 1, 2, 0],
         [1, 2, 0, 1, 2]],
 
        [[0, 1, 2, 0, 1],
         [2, 0, 1, 2, 0],
         [1, 2, 0, 1, 2]]]),
 array([[[0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4]],
 
        [[0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4]]])]

In [61]:
# this should be the shape of our output also
np.broadcast(i1, i2).shape

(2, 3, 5)

slice dimension moves to the back again

In [62]:
a[i1, : ,i2].shape

(2, 3, 5, 4)

In [93]:
a[i1, : ,i2]

array([[[[7, 2, 0, 5],
         [7, 3, 0, 9],
         [3, 7, 3, 8],
         [6, 0, 8, 5],
         [0, 8, 2, 3]],

        [[5, 8, 7, 0],
         [0, 0, 9, 7],
         [5, 7, 0, 1],
         [3, 2, 2, 8],
         [9, 0, 5, 7]],

        [[1, 0, 1, 5],
         [1, 8, 2, 0],
         [7, 7, 8, 5],
         [6, 4, 2, 8],
         [3, 5, 4, 2]]],


       [[[7, 2, 0, 5],
         [7, 3, 0, 9],
         [3, 7, 3, 8],
         [6, 0, 8, 5],
         [0, 8, 2, 3]],

        [[5, 8, 7, 0],
         [0, 0, 9, 7],
         [5, 7, 0, 1],
         [3, 2, 2, 8],
         [9, 0, 5, 7]],

        [[1, 0, 1, 5],
         [1, 8, 2, 0],
         [7, 7, 8, 5],
         [6, 4, 2, 8],
         [3, 5, 4, 2]]]])

EXCEPT, when they dont. If the slice is the first thing, it is taken as the first dimension


In [63]:
a[:, i1 ,i2].shape

(3, 2, 3, 5)

## Resources
https://www.youtube.com/watch?v=o0EacbIbf58&t=1680s


https://stackoverflow.com/questions/53841497/why-does-numpy-mixed-basic-advanced-indexing-depend-on-slice-adjacency

https://stackoverflow.com/questions/46325897/non-adjacent-slicing-of-numpy-multidimensional-array-in-python?noredirect=1&lq=1

https://numpy.org/doc/stable/reference/arrays.indexing.html#combining-advanced-and-basic-indexing

https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d


https://github.com/numpy/numpy/pull/6075