# ASPP 2021
## Advanced Numpy Excercises Topic 4


In [1]:
# Make sure that plots are displayed in the notebook
%matplotlib inline

# plotting library
from matplotlib import pyplot as plt
# for obvious reasons
import numpy as np

# a small number of handy tools that may be useful for these exercises
import tools

**4.1** Go full suicide mode: switch off all errors and divide by zero like there's no tomorrow!! Then switch the errors back on.

In [4]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0
    
np.geterr()

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

**4.2** Consider the following problem. You have a long 1D numpy array. You want to select one out of every two at random, i.e. either the first OR the second, then either the third OR the fourth, etc.

**tip 1** it may be useful to reshape the array

**tip 2** there are many ways of doing this. You could try fancy indexing or maybe read the documentation of `np.chose`


(optional) can you generalize your code for more dimensions?


-- https://stackoverflow.com/questions/26325652/fastest-way-to-keep-one-element-over-two-from-long-numpy-arrays

In [24]:
a = np.array([1,2,25,13,10,9,4,5])
k = 2
aa = a.reshape(-1, k)  # 1dim -> 2dim
aa

array([[ 1,  2],
       [25, 13],
       [10,  9],
       [ 4,  5]])

In [21]:
i = np.random.randint(k, size = aa.shape[0]) # random indices
i


array([0, 0, 0, 1])

In [22]:
aa[np.arange(4),i]

array([ 1, 25, 10,  5])

In [23]:
np.choose(i, aa.T)

array([ 1, 25, 10,  5])

In [28]:
np.arange(8).reshape(2,4).flatten().shape

(8,)